/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package simulation;

import org.junit.jupiter.api.Test;

import simulation.Simulation;

import static org.junit.jupiter.api.Assertions.*;

class SimulationTest {

}
