/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package simulation;

import engine.Engine;
import org.apache.commons.cli.*;
import utils.RatioUtils;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.concurrent.TimeUnit;

public class Simulation {

    private Board board;
    private Integer duration; // Liczba tur
    private Integer time; // Aktualna ture

    public Simulation(int n, int m, int duration, int gangSize) {
        this.board = new Board(n, m);
        this.duration = duration;
        // Populate board
        board.populate(gangSize, RatioUtils.getRatio());
        // Set time to 0
        this.time = 0;
        Engine.render(board, time);
    }

    public void run() {
        // Main loop
        while (time < duration) {
            // Move all agents
            board.move();
            // Fight
            board.fight();
            // Render board
            Engine.render(board, time);

            // Wait some time
            try {
                TimeUnit.SECONDS.sleep(1);
            } catch (InterruptedException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
            time++;
        }
    }

    public void printStats() {
        // Wypisz koniec na stoud
        Engine.renderStats(board, time);
        // Wypisz statytki na stdout i do pliku
    }

    public static void main(String[] args) {
        Options options = new Options();
        Option n = new Option("n", "nDim", true, "n - dimension of board");
        n.setRequired(true);
        options.addOption(n);

        Option m = new Option("m", "mDim", true, "m - dimension of board");
        m.setRequired(true);
        options.addOption(m);

        Option d = new Option("d", "duration", true, "Duration of the simulation");
        d.setRequired(true);
        options.addOption(d);

        Option gs = new Option("gs", "gangSize", true, "Size of gang");
        gs.setRequired(true);
        options.addOption(gs);

        HelpFormatter formatter = new HelpFormatter();
        CommandLineParser parser = new DefaultParser();
        CommandLine cmd;
        try {
            cmd = parser.parse(options, args);
        } catch (ParseException e) {
            System.out.println(e.getMessage());
            formatter.printHelp("Reuired flags:", options);
            System.exit(1);
            return;
        }
        int newN = Integer.parseInt(cmd.getOptionValue("n"));
        int newM = Integer.parseInt(cmd.getOptionValue("m"));
        int newDuration = Integer.parseInt(cmd.getOptionValue("d"));
        int newGangSize = Integer.parseInt(cmd.getOptionValue("gs"));

        // Create new simulation
        Simulation simulation = new Simulation(newN, newM, newDuration, newGangSize);
        // Start the simulation
        simulation.run();
        // Print stats
        simulation.printStats();
    }
}
