/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package simulation;

import engine.Engine;
import utils.RatioUtils;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Scanner;
import java.util.concurrent.TimeUnit;

public class Simulation {

    private Board board;
    private Integer duration; // Liczba tur
    private Integer time; // Aktualna ture

    public Simulation(int n, int m, int duration, int gangSize) {
        this.board = new Board(n, m);
        this.duration = duration;
        // Populate board
        board.populate(gangSize, RatioUtils.getRatio());
        // Set time to 0
        this.time = 0;
        Engine.render(board, time);
    }

    public void run() {
        // Main loop
        while (time < duration) {
            // Move all agents
            board.move();
            // Fight
            board.fight();
            // Render board
            Engine.render(board, time);

            // Wait some time
            try {
                TimeUnit.SECONDS.sleep(1);
            } catch (InterruptedException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
            time++;
        }
    }

    public void printStats() {
        // Wypisz koniec na stoud
        Engine.renderStats(board, time);
        // Wypisz statytki na stdout i do pliku
    }

    public static void main(String[] args) {
        // TODO Parse args
        //menu
        int x = 0;
        int tempDuration=1;
        int tempGangSize=1;
        int tempN=10;
        int tempM=10;
        while(x!=4) {
            System.out.print("\033[H\033[2J");
            System.out.println("CHOOSE WHAT DO YOU WANT TO DO: ");
            System.out.println("1. Set duration of the simulation. \n2. Set number of agents per organisation \n3. Set dimensions of the board \n4. Exit");
            Scanner sc = new Scanner(System.in);
            x = sc.nextInt();
            switch (x) {
                case 1: {
                    System.out.print("Duration: ");
                    Scanner input = new Scanner(System.in);
                    tempDuration = input.nextInt();
                    break;
                }
                case 2: {
                    System.out.print("Gang size: ");

                    Scanner input = new Scanner(System.in);
                    tempGangSize = input.nextInt();
                    break;
                }
                case 3: {
                    System.out.print("n: ");
                    Scanner input = new Scanner(System.in);
                    tempN = input.nextInt();
                    System.out.print("m: ");
                    input = new Scanner(System.in);
                    tempM = input.nextInt();
                    break;
                }
                case 4: {
                    break;
                }
            }
        }




        // Create new simulation
        Simulation simulation = new Simulation(tempN, tempM, tempDuration, tempGangSize);
        // Start the simulation
        simulation.run();
        // Print stats
        simulation.printStats();
    }
}
